version: '3.7'

services:
  my-backend:
    image: # asia.gcr.io/global-timer-347010/my-backend02:8.0
    build:
      context: .
      dockerfile: Dockerfile
    # volumes:
    #   - ./src/:/myfolder/src/
    # env_file:
    #   - ./.env.prod
    ports:
      - 3000:3000

  # my-database:
  #   image: mysql:latest
  #   environment:
  #     MYSQL_DATABASE: 'mydocker02'
  #     MYSQL_ROOT_PASSWORD: 'root'
  #   ports:
  #     - 3306:3306
