version: '3.7'

services:
  my-backend:
    image: asia.gcr.io/solid-feat-349705/team-project:1.34
    platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
